/**
 * Generates docs/citation-audit-checklist.md — the worklist a human needs in order
 * to close out primary-source verification on the taikyo golden set.
 *
 *   npm run audit:citations
 *
 * Entries whose source is one of our own fixtures are excluded: they assert no
 * judgment, so there is nothing to look up. Everything else is grouped by the
 * authority it cites, because a reviewer pulls one 判例集 volume and clears every
 * entry resting on it at once — the unit of work is the citation, not the entry.
 */

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { OPEN_QUESTIONS, groupCorpus, readCorpus } from "./lib/citation-groups.ts";

const outPath = fileURLToPath(new URL("../docs/citation-audit-checklist.md", import.meta.url));

const corpus = readCorpus();
const { groups: ordered, syntheticCount: synthetic } = groupCorpus(corpus);
const outstanding = ordered.reduce((n, g) => n + g.entries.length, 0);
const verifiedTotal = ordered.reduce((n, g) => n + g.verified, 0);

const L: string[] = [];
L.push("# Citation audit checklist — taikyo golden set");
L.push("");
L.push(`_Generated by \`npm run audit:citations\` from \`tests/golden-set/taikyo-corpus.json\` v${corpus.version}. Do not edit by hand._`);
L.push("");
L.push("## Why this exists");
L.push("");
L.push(
  "`source.verified` is true only where a human has confirmed a citation against the primary text, and the " +
    "validator enforces that it implies `verification_status == \"primary_source_verified\"`. That count is currently " +
    "**zero**: the build environment cannot reach 裁判所, 国土交通省 or RETIO, so citations were cross-read against " +
    "secondary summaries at best. That cross-reading already caught two real errors, which is the argument for " +
    "doing this properly rather than flipping the flag.",
);
L.push("");
L.push("**Nothing derived from this corpus should reach a user until the groups below are cleared.**");
L.push("");
L.push("## Scoreboard");
L.push("");
L.push("| | Count |");
L.push("| --- | ---: |");
L.push(`| Entries in corpus | ${corpus.cases.length} |`);
L.push(`| Our own fixtures — nothing to verify | ${synthetic} |`);
L.push(`| **Entries asserting an external source** | **${outstanding}** |`);
L.push(`| Distinct authorities to pull | ${ordered.length} |`);
L.push(`| Already primary-source verified | ${verifiedTotal} |`);
L.push("");
L.push("## Progress");
L.push("");
L.push("| Authority | Where | Entries | Verified | Open questions |");
L.push("| --- | --- | ---: | ---: | ---: |");
for (const g of ordered) {
  const q = OPEN_QUESTIONS[g.key]?.length ?? 0;
  const state = g.verified === g.entries.length ? "done" : `${g.verified}/${g.entries.length}`;
  L.push(`| ${g.key} | ${g.where} | ${g.entries.length} | ${state} | ${q > 0 ? q : "-"} |`);
}
L.push("");
L.push("## How to clear a group");
L.push("");
L.push(
  "1. Pull the primary text named under **Where**.\n" +
    "2. Answer every question under **Confirm**.\n" +
    "3. If the authority does not say what we claim, fix the entry — do not weaken the claim to fit.\n" +
    "4. Sign the whole group off in one command, recording what you actually read:\n\n" +
    "   ```sh\n" +
    "   npm run audit:status                     # where things stand\n" +
    "   npm run audit:verify -- --group \"<authority>\" --evidence \"<reporter and page, or URL>\"\n" +
    "   npm run audit:verify -- --group \"<authority>\" --evidence \"...\" --apply\n" +
    "   ```\n\n" +
    "   It is dry by default, refuses to run without evidence, and stamps the evidence onto every\n" +
    "   entry in the group. Editing the JSON by hand works too, but an authority backs up to 17\n" +
    "   entries and that is 17 chances to set the flag on the wrong one.\n" +
    "5. Re-run `npm run validate:corpus` (it rejects `verified: true` without the status) and `npm run audit:citations`.",
);
L.push("");
L.push("---");
L.push("");

for (const g of ordered) {
  L.push(`## ${g.key}`);
  L.push("");
  L.push(`**Where:** ${g.where}`);
  if (g.spellings.size > 1) {
    L.push("");
    L.push(`**Cited in the corpus as:** ${[...g.spellings].map((s) => `\`${s}\``).join(" · ")}`);
  }
  L.push("");
  const questions = OPEN_QUESTIONS[g.key];
  if (questions) {
    L.push("**Confirm:**");
    L.push("");
    for (const q of questions) L.push(`- [ ] ${q}`);
    L.push("");
  } else {
    L.push("**Confirm:**");
    L.push("");
    L.push("- [ ] The authority exists as cited and says what the entries below rely on.");
    L.push("");
  }
  L.push(`**Entries resting on it (${g.entries.length}):**`);
  L.push("");
  L.push("| | Entry | Pattern | Verdict | Status | Clause (opening) |");
  L.push("| --- | --- | --- | --- | --- | --- |");
  for (const e of g.entries.sort((a, b) => a.id.localeCompare(b.id))) {
    const head = e.clause_text.slice(0, 34).replace(/\|/g, "\\|");
    L.push(
      `| [ ] | \`${e.id}\` | ${e.expected_code} | ${e.expected_verdict} | ${e.source.verification_status} | ${head}… |`,
    );
  }
  L.push("");
}

L.push("---");
L.push("");
L.push("## Notes carried on individual entries");
L.push("");
L.push("Entries whose `source.note` records a correction or an open question:");
L.push("");
for (const e of corpus.cases) {
  const note = e.source.note;
  if (!note) continue;
  if (!/CITATION CORRECTED|CITATION CONFIRMED|CONTESTED FIGURE/.test(note)) continue;
  L.push(`- **\`${e.id}\`** — ${note.split(". ").slice(0, 2).join(". ")}.`);
}
L.push("");

writeFileSync(outPath, L.join("\n"));
console.log(`wrote ${outPath}`);
console.log(`  ${outstanding} entries asserting an external source, across ${ordered.length} authorities`);
console.log(`  ${synthetic} of our own fixtures excluded`);
